parameters:
    database_driver:   pdo_mysql
    database_host:     mysql.alwaysdata.com
    database_port:     ~
    database_name:     etuwebdev_projetsncf
    database_user:     etuwebdev_test
    database_password: test

    mailer_transport:  smtp
    mailer_host:       127.0.0.1
    mailer_user:       ~
    mailer_password:   ~

    locale:            en
    secret:            ThisTokenIsNotSoSecretChangeIt
