lpdw_twitter:
    resource: "@LPDWTwitterBundle/Controller/"
    type:     annotation
    prefix:   /

lpdw_google_map:
    resource: "@LPDWGoogleMapBundle/Controller/"
    type:     annotation
    prefix:   /

lpdw_foursquare:
    resource: "@LPDWFoursquareBundle/Controller/"
    type:     annotation
    prefix:   /

lpdw_sncf:
    resource: "@LPDWSncfBundle/Controller/"
    type:     annotation
    prefix:   /

lpdw_client:
    resource: "@LPDWClientBundle/Controller/"
    type:     annotation
    prefix:   /

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

EndroidTwitterBundle:
    resource:   "@EndroidTwitterBundle/Controller/"
    type:       annotation
    prefix:     /twitterapi

# Internal routing configuration to handle ESI
# ****** WARNING ******
# This route should be enabled with caution as it can open a security vulnerability
# see http://symfony.com/blog/security-release-symfony-2-0-20-and-2-1-5-released for more information
# ****** WARNING ******
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
